version: "3.9"
services:
  app:
    image: local/tendenci:local
    ## command: python club/manage.py runserver 8000
    ## command: /bin/true
    platform: "linux/amd64"
    environment:
      ## GOOGLE_CLOUD_PROJECT: rf-tendenci-test
      CACHE_LOCATION: 'cache:11211'
      CACHE_BACKEND: 'django.core.cache.backends.memcached.MemcachedCache'
      DEBUG: True
      PORT: 8000
      INSTANCE_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME}
      PGDATABASE: ${PGDATABASE}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGUSER: ${PGUSER}
    volumes:
      ## - ./club/:/app/
      - ./django.env:/app/.env
      - cloudsql:/cloudsql
      - .:/work
      - root:/root:rw
    ports:
      - "8000:8000"
    depends_on:
      - cache
      - cloudsql
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
  cloudsql:
    image: local/tendenci:local
    build:
      context: .
      dockerfile: Dockerfile
    platform: "linux/amd64"
    command: cloud-sql-proxy --unix-socket /cloudsql/ ${INSTANCE_CONNECTION_NAME}
    volumes:
      - cloudsql:/cloudsql
      - root:/root:rw
  agent:
    container_name: newrelic-infra
    build:
      context: .
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

networks:
  tendenci:
    driver: bridge

volumes:
  cloudsql:
  root:
