apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tendenci
spec:
  template:
    spec:
      containers:
        - name: tendenci
          image: gcr.io/rf-tendenci-test/tendenci
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: rf-tendenci-test
            - name: CACHE_BACKEND
              value: 'django.core.cache.backends.memcached.MemcachedCache'
            - name: CACHE_LOCATION
              value: '127.0.0.1:11211'
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 8080
            timeoutSeconds: 240
          volumeMounts:
            - mountPath: /app/.env
              name: dotenv
        - name: cache
          image: memcached
          command:
            - memcached
            - -m 64
          resources:
            limits:
              cpu: 500m
              memory: 256M
      serviceAccountName: tendenci-service@club-twbc-org.iam.gserviceaccount.com
      timeoutSeconds: 300
      volumes:
        - name: dotenv
          secret:
            items:
              - key: latest
                path: .
            secretName: django_settings
